# Generated by Django 4.2.23 on 2026-07-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ashtrih', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineOneCTTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('series', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('is_bel_receiver', models.BooleanField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_offline', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OfflineOneCTTNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('available_quantity', models.PositiveIntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_offline', models.BooleanField(db_index=True, default=False)),
                ('model_name', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='ashtrih.offlinemodelnames')),
                ('onec_ttn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aonec.offlineonecttn')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
