# Generated by Django 4.2.23 on 2026-03-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashtrih', '0002_offlineworkplaces_offlineprotocols'),
        ('aonec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineonecttnitem',
            name='name',
        ),
        migrations.AddField(
            model_name='offlineonecttnitem',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ashtrih.offlinemodels'),
            preserve_default=False,
        ),
    ]
