# Generated by Django 4.2.23 on 2026-04-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aonec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineonecttnitem',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
