# Generated by Django 4.2.23 on 2026-05-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aonec', '0002_offlineonecttnitem_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineonecttn',
            name='shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
