# Generated by Django 4.2.23 on 2026-03-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashtrih', '0002_offlineworkplaces_offlineprotocols'),
        ('aonec', '0002_remove_offlineonecttnitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineonecttnitem',
            name='model',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='ashtrih.offlinemodels'),
        ),
    ]
