# Generated by Django 4.2.23 on 2026-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aonec', '0003_offlineonecttn_shipment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineonecttn',
            name='is_bel_receiver',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
