# Generated by Django 4.2.23 on 2026-07-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_date', models.DateTimeField(auto_now_add=True)),
                ('solve_date', models.DateTimeField(blank=True, null=True)),
                ('is_solved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=18)),
                ('state', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('is_shipment', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=2)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseTTN',
            fields=[
                ('ttn_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_close', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ttn_number'],
                'managed': False,
            },
        ),
    ]
