# Generated by Django 4.2.23 on 2025-07-15 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTTN',
            fields=[
                ('ttn_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_close', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-ttn_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='warehouseproduct',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='warehouse_ttn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousettn'),
        ),
    ]
