# Generated by Django 4.2.23 on 2026-10-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldProduct',
        ),
    ]
