# Generated by Django 4.2.23 on 2026-03-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=18)),
                ('state', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
