# Generated by Django 4.2.23 on 2026-04-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_oldproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='WarehouseProduct',
        ),
    ]
