# Generated by Django 4.2.23 on 2025-07-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehousettn_alter_warehouseproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
