# Generated by Django 4.2.23 on 2025-07-17 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0006_protocols_typesofwork_workplaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0003_warehouseproduct_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ttn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='shtrih.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
                ('warehouse_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouseaction')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct')),
                ('warehouse_ttn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousettn')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
