# Generated by Django 4.2.23 on 2026-06-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_delete_shipment_delete_warehouseproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_date', models.DateTimeField(auto_now_add=True)),
                ('solve_date', models.DateTimeField(blank=True, null=True)),
                ('is_solved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
