# Generated by Django 4.2.23 on 2025-07-23 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onec', '0001_initial'),
        ('warehouse', '0004_warehouseproducthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='warehouseproducthistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehouseproducthistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='warehouseproducthistory',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehouseproducthistory',
            name='warehouse_action',
        ),
        migrations.RemoveField(
            model_name='warehouseproducthistory',
            name='warehouse_product',
        ),
        migrations.RemoveField(
            model_name='warehouseproducthistory',
            name='warehouse_ttn',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='date',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='ttn_number',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='warehouse_action',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='warehouse_ttn',
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='onec_ttn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onec.onecttn'),
        ),
        migrations.AddField(
            model_name='warehousettn',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehousettn',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.pallet'),
        ),
        migrations.AddField(
            model_name='warehousettn',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehousettn',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehousettn',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehousettn',
            name='warehouse_action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseaction'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Palleting',
        ),
        migrations.DeleteModel(
            name='WarehouseProductHistory',
        ),
        migrations.AddField(
            model_name='warehousedo',
            name='warehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct'),
        ),
        migrations.AddField(
            model_name='warehousedo',
            name='warehouse_ttn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousettn'),
        ),
    ]
