# Generated by Django 4.2.23 on 2025-07-29 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0002_onecttn_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0006_remove_warehouseproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='onec_ttn',
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='is_shipment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('onec_ttn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onec.onecttn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
