# Generated by Django 4.2.23 on 2025-09-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_pallet_create_at_pallet_update_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pallet',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='typeofwork',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='warehouseaction',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='warehousedo',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='warehouseproduct',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='warehousettn',
            options={'managed': False, 'ordering': ['-ttn_number']},
        ),
    ]
