# Generated by Django 4.2.23 on 2026-06-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woffline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinepallet',
            name='barcode',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='offlinepallet',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='offlinewarehouseaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='offlinewarehousedo',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='offlinewarehousettn',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='offlinewarehousettn',
            name='is_close',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='offlinewarehousettn',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='offlinewarehousettn',
            name='is_offline',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='offlinewarehousettn',
            name='update_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
