# Generated by Django 4.2.23 on 2026-04-03 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aonec', '0001_initial'),
        ('woffline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinepallet',
            name='ttn_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woffline.offlinewarehousettn'),
        ),
        migrations.AlterField(
            model_name='offlinewarehousedo',
            name='old_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woffline.offlineoldproduct'),
        ),
        migrations.AlterField(
            model_name='offlinewarehousettn',
            name='onec_ttn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aonec.offlineonecttn'),
        ),
    ]
