# Generated by Django 4.2.23 on 2026-10-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashtrih', '0002_offlinemodels_relevance_alter_offlinemodels_code'),
        ('woffline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinewarehousedo',
            name='old_product',
        ),
        migrations.AlterField(
            model_name='offlinewarehousedo',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='ashtrih.offlineproducts'),
        ),
        migrations.DeleteModel(
            name='OfflineOldProduct',
        ),
    ]
