# Generated by Django 4.2.23 on 2026-03-13 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aonec', '0001_initial'),
        ('woffline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineshipment',
            name='onec_ttn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aonec.offlineonecttn'),
        ),
        migrations.AlterField(
            model_name='offlineshipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offlineshipment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woffline.offlinewarehouse'),
        ),
        migrations.AlterField(
            model_name='offlineshipment',
            name='warehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woffline.offlinewarehouseproduct'),
        ),
        migrations.AlterField(
            model_name='offlinewarehousedo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offlinewarehousedo',
            name='warehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woffline.offlinewarehouseproduct'),
        ),
        migrations.AlterField(
            model_name='offlinewarehousedo',
            name='warehouse_ttn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woffline.offlinewarehousettn'),
        ),
        migrations.AlterField(
            model_name='offlinewarehousettn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offlinewarehousettn',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woffline.offlinewarehouse'),
        ),
        migrations.AlterField(
            model_name='offlinewarehousettn',
            name='warehouse_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woffline.offlinewarehouseaction'),
        ),
    ]
