# Generated by Django 4.2.23 on 2026-06-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woffline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepallet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offlinewarehouseaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offlinewarehousettn',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
