# Generated by Django 4.2.23 on 2026-03-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woffline', '0002_alter_offlineshipment_onec_ttn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinewarehouseproduct',
            name='is_offline',
            field=models.BooleanField(default=False),
        ),
    ]
