# Generated by Django 4.2.23 on 2026-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woffline', '0002_alter_offlinepallet_ttn_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineoldproduct',
            name='is_shipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offlinewarehousedo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
