# Generated by Django 4.2.23 on 2026-05-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woffline', '0003_offlineoldproduct_is_shipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinewarehouseaction',
            name='operation',
            field=models.CharField(default='+', max_length=2),
        ),
    ]
