# Generated by Django 4.2.23 on 2026-06-03 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashtrih', '0002_alter_offlineproducts_color_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('woffline', '0004_offlinewarehouseaction_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineNotPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_date', models.DateTimeField(auto_now_add=True)),
                ('solve_date', models.DateTimeField(blank=True, null=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('bloom_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='ashtrih.offlineproducts')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='woffline.offlinewarehouse')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
