# Generated by Django 4.2.23 on 2026-06-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woffline', '0005_offlinenotpackaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinenotpackaging',
            name='is_offline',
            field=models.BooleanField(default=True),
        ),
    ]
