# Generated by Django 4.2.23 on 2026-06-03 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ashtrih', '0002_alter_offlineproducts_color_code_and_more'),
        ('woffline', '0006_offlinenotpackaging_is_offline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinenotpackaging',
            name='bloom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offlinenotpackaging',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='ashtrih.offlineproducts'),
        ),
        migrations.AlterField(
            model_name='offlinenotpackaging',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woffline.offlinewarehouse'),
        ),
    ]
