from django.urls import path

from apps.woffline.views.warhouse_sync import FullWarehouseSyncView, WarehouseSyncView
from apps.woffline.views.type_of_work import OfflineTypeOfWorkListView
from apps.woffline.views.warehouse_action import OfflineWarehouseActionListView, OfflineWarehouseActionRetrieveView
from apps.woffline.views.warehouse import OfflineWarehouseListView
from apps.woffline.views.pallet import (
    OfflinePalletCreateByTTNAPIView,
    OfflinePalletListCreateAPIView,
    OfflinePalletRetrieveUpdateDestroyView,
    OfflinePalletWithProductsListAPIView,
    OfflinePalletDecomposeAPIView,
    OfflinePalletByBarcodeWithProductsListAPIView,
    OnlyOfflinePalletByBarcodeWithProductsListAPIView,
    OnlyOfflinePalletCreateByTTNAPIView,
)
from apps.woffline.views.warehouse_ttn import (
    OfflineWarehouseTTNByUserIdAPIView,
    OfflineWarehouseTTNCreateAPIView,
    OfflineWarehouseTTNListAPIView,
    OfflineWarehouseTTNProductsAPIView,
    OfflineWarehouseTTNRetrieveAPIView,
    OfflineWarehouseTTNProductsByUserIdAPIView,
    OfflineWarehouseTTNRetrieveUpdateDestroyAPIView,
    OfflineWarehouseTTNByOneCProductsAPIView,
    OnlyOfflineWarehouseTTNRetrieveUpdateDestroyAPIView,
    OnlyOfflineWarehouseTTNProductsByUserIdAPIView,
    OnlyOfflineWarehouseTTNByOneCProductsAPIView,
    OnlyOfflineWarehouseTTNListAPIView,
)
from apps.woffline.views.warehouse_do import (
    OfflineWarehouseDoBarcodeAPIView,
    OfflineWarehouseDoListAPIView,
    OfflineWarehouseDoRetrieveAPIView,
    OfflineWarehouseDoRetrieveUpdateDestroyAPIView,
    OfflineWarehouseDoPalletAPIView,
    OfflineWarehouseDoShipmentAPIView,
    OfflineWarehouseDoShipmentDeleteAPIView,
    OnlyOfflineWarehouseDoShipmentDeleteAPIView,
    OnlyOfflineWarehouseDoShipmentAPIView,
    OnlyOfflineWarehouseDoPalletAPIView,
    OnlyOfflineWarehouseDoBarcodeAPIView,
    OnlyOfflineWarehouseDoRetrieveUpdateDestroyAPIView,
)

urlpatterns = [
    path('full_sync/', FullWarehouseSyncView.as_view()),
    path('sync/', WarehouseSyncView.as_view()),
    path('warehouse/typeofwork/', OfflineTypeOfWorkListView.as_view(), name='type-of-work-list'),
    path('warehouse/action/', OfflineWarehouseActionListView.as_view(), name='action-list'),
    path('warehouse/action/<int:pk>/', OfflineWarehouseActionRetrieveView.as_view(),
         name='detailed-action-list'),
    path('warehouse/warehouse/', OfflineWarehouseListView.as_view(), name='warehouse-list'),
    path('warehouse/pallet/', OfflinePalletListCreateAPIView.as_view(), name='pallet-list'),
    path('warehouse/pallet/<int:pk>/', OfflinePalletRetrieveUpdateDestroyView.as_view(), name='pallet-update'),
    path('warehouse/pallet/generate/', OfflinePalletCreateByTTNAPIView.as_view()),  # not working without server db
    path('warehouse/pallet/offline_generate/', OnlyOfflinePalletCreateByTTNAPIView.as_view(), name='pallet-create'),
    path('warehouse/pallet/pallet_with_products/', OfflinePalletWithProductsListAPIView.as_view(),
         name='pallet-with-products-list'),
    path('warehouse/pallet/pallet_with_products_by_barcode/', OfflinePalletByBarcodeWithProductsListAPIView.as_view(),
         name='pallet-by-barcode-list'),
    path('warehouse/pallet/offline_pallet_with_products_by_barcode/',
         OnlyOfflinePalletByBarcodeWithProductsListAPIView.as_view(),
         name='offline-pallet-by-barcode-list'),
    path('warehouse/pallet/decompose/', OfflinePalletDecomposeAPIView.as_view(), name='decompose'),
    path('warehouse/ttn/', OfflineWarehouseTTNListAPIView.as_view(), name='warehouse-ttn-list'),
    path('warehouse/offline_ttn/', OnlyOfflineWarehouseTTNListAPIView.as_view(), name='offline-warehouse-ttn-list'),
    path('warehouse/ttn/create/', OfflineWarehouseTTNCreateAPIView.as_view(), name='warehouse-ttn-create'),
    path('warehouse/ttn/retrieve/<str:ttn_number>/', OfflineWarehouseTTNRetrieveAPIView.as_view(),
         name='warehouse-ttn-retrieve'),
    path('warehouse/ttn/update/<str:ttn_number>/', OfflineWarehouseTTNRetrieveUpdateDestroyAPIView.as_view(),
         name='warehouse-ttn-update'),
    path('warehouse/ttn/user/', OfflineWarehouseTTNByUserIdAPIView.as_view(), name='warehouse-ttn-user'),
    path('warehouse/ttn/products/<str:ttn_number>/', OfflineWarehouseTTNProductsAPIView.as_view(),
         name='warehouse-ttn-products-list'),
    path('warehouse/ttn/product/user/', OfflineWarehouseTTNProductsByUserIdAPIView.as_view(),
         name='warehouse-ttn-products-by-user-list'),
    path('warehouse/ttn/offline_product/user/', OnlyOfflineWarehouseTTNProductsByUserIdAPIView.as_view(),
         name='offline-warehouse-ttn-products-by-user-list'),
    path('warehouse/ttn/products_by_onec/', OfflineWarehouseTTNByOneCProductsAPIView.as_view(),
         name='warehouse-ttn-products-by-onec-list'),
    path('warehouse/ttn/offline_products_by_onec/', OnlyOfflineWarehouseTTNByOneCProductsAPIView.as_view(),
         name='offline-warehouse-ttn-products-by-onec-list'),
    path('warehouse/ttn/offline_update/<str:ttn_number>/',
         OnlyOfflineWarehouseTTNRetrieveUpdateDestroyAPIView.as_view(),
         name='offline-warehouse-ttn-update'),
    path('warehouse/do/', OfflineWarehouseDoListAPIView.as_view(), name='warehousedo-list'),
    path('warehouse/do/retrieve/<int:pk>/', OfflineWarehouseDoRetrieveAPIView.as_view(), name='warehousedo-retrieve'),
    path('warehouse/do/update/<int:pk>/', OfflineWarehouseDoRetrieveUpdateDestroyAPIView.as_view(),
         name='warehousedo-update'),
    path('warehouse/do/barcode/', OfflineWarehouseDoBarcodeAPIView.as_view(), name='warehousedo-barcode'),
    path('warehouse/do/pallet/', OfflineWarehouseDoPalletAPIView.as_view(), name='warehousedo-pallet'),
    path('warehouse/do/shipment/', OfflineWarehouseDoShipmentAPIView.as_view(), name='warehouse-shipment'),
    path('warehouse/do/shipment/delete_barcode/', OfflineWarehouseDoShipmentDeleteAPIView.as_view(),
         name='warehousedo-shipment-delete'),
    path('warehouse/do/shipment/offline_delete_barcode/', OnlyOfflineWarehouseDoShipmentDeleteAPIView.as_view(),
         name='offline-warehousedo-shipment-delete'),
    path('warehouse/do/offline_shipment/', OnlyOfflineWarehouseDoShipmentAPIView.as_view(),
         name='offline-warehouse-shipment'),
    path('warehouse/do/offline_pallet/', OnlyOfflineWarehouseDoPalletAPIView.as_view(),
         name='offline-warehousedo-pallet'),
    path('warehousedo/offline_barcode/', OnlyOfflineWarehouseDoBarcodeAPIView.as_view(),
         name='offline-warehousedo-barcode'),
    path('warehouse/do/offline_update/<int:pk>/', OnlyOfflineWarehouseDoRetrieveUpdateDestroyAPIView.as_view(),
         name='offline-warehousedo-retrieve-update-destroy'),
]
