# Generated by Django 4.2.23 on 2025-09-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_role_create_at_role_update_at_userroles_create_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userroles',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
