# Generated by Django 4.2.23 on 2026-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashtrih', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinemodels',
            name='relevance',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='offlinemodels',
            name='code',
            field=models.IntegerField(db_index=True),
        ),
    ]
