# Generated by Django 4.2.23 on 2026-03-19 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashtrih', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineWorkplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing', models.CharField(db_column='housing', max_length=3)),
                ('type_of_work', models.SmallIntegerField(db_column='type_of_work_id')),
                ('computer_number', models.CharField(db_column='computer_number', max_length=2)),
                ('create_at', models.DateTimeField(db_column='create_at')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OfflineProtocols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_column='work_date')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='ashtrih.offlineproducts')),
                ('workplace', models.ForeignKey(db_column='workplace_id', on_delete=django.db.models.deletion.CASCADE, to='ashtrih.offlineworkplaces')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
