# Generated by Django 4.2.23 on 2026-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashtrih', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineproducts',
            name='color_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='offlineproducts',
            name='russian_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
