# Generated by Django 4.2.23 on 2025-09-09 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0002_onecttn_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecttn',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onecttn',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onecttnitem',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onecttnitem',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
