# Generated by Django 4.2.23 on 2025-09-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0003_onecttn_create_at_onecttn_update_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onecttn',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='onecttnitem',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
