# Generated by Django 4.2 on 2025-03-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'model_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omega_model_id', models.IntegerField()),
                ('omega_variant_id', models.IntegerField()),
                ('code', models.IntegerField()),
                ('diagonal', models.FloatField()),
                ('weight', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product_warranty', models.IntegerField()),
                ('storage_warranty', models.IntegerField()),
                ('variant_code', models.CharField(max_length=20)),
                ('design_code', models.CharField(max_length=20)),
                ('letter_part', models.CharField(max_length=25)),
                ('numeric_part', models.CharField(max_length=20)),
                ('execution_part', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'models',
                'managed': False,
            },
        ),
    ]
