# Generated by Django 4.2.23 on 2026-02-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(blank=True, db_column='color_code', max_length=4, null=True)),
                ('russian_title', models.CharField(blank=True, db_column='russian_title', max_length=50, null=True)),
            ],
            options={
                'db_table': 'colors',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('used_quantity', models.IntegerField()),
                ('declaration_number', models.CharField(max_length=50)),
                ('declaration_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'consignments',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'model_colors',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelNames',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'model_names',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omega_model_id', models.IntegerField()),
                ('omega_variant_id', models.IntegerField()),
                ('code', models.IntegerField()),
                ('diagonal', models.FloatField()),
                ('weight', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product_warranty', models.IntegerField()),
                ('storage_warranty', models.IntegerField()),
                ('variant_code', models.CharField(max_length=20)),
                ('design_code', models.CharField(max_length=20)),
                ('letter_part', models.CharField(max_length=25)),
                ('numeric_part', models.CharField(max_length=20)),
                ('execution_part', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'models',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='number')),
                ('digit', models.IntegerField(db_column='digit')),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Production_codes',
            fields=[
                ('code', models.IntegerField(db_column='code', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=70)),
                ('nameplate', models.BooleanField(db_column='nameplate')),
            ],
            options={
                'db_table': 'production_codes',
                'ordering': ['-code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=18)),
                ('state', models.IntegerField()),
                ('nameplate', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Protocols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_column='work_date')),
            ],
            options={
                'db_table': 'protocols',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypesOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('order', models.SmallIntegerField(db_column='order')),
            ],
            options={
                'db_table': 'types_of_work',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing', models.CharField(db_column='housing', max_length=3)),
                ('computer_number', models.CharField(db_column='computer_number', max_length=2)),
                ('create_at', models.DateTimeField(db_column='create_at')),
                ('version', models.CharField(db_column='version', max_length=10)),
            ],
            options={
                'db_table': 'workplaces',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
