# Generated by Django 4.2.23 on 2026-10-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duplicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(db_column='count')),
            ],
            options={
                'db_table': 'duplicates',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShtrihUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valuable_components',
            fields=[
                ('code', models.IntegerField(db_column='code', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('active', models.BooleanField(db_column='active')),
                ('create_at', models.DateTimeField(db_column='create_at')),
            ],
            options={
                'db_table': 'valuable_components',
                'ordering': ['code'],
                'managed': False,
            },
        ),
    ]
