# Generated by Django 4.2 on 2025-04-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('used_quantity', models.IntegerField()),
                ('declaration_number', models.CharField(max_length=50)),
                ('declaration_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'consignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=18)),
                ('color_id', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField()),
                ('nameplate', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('cleared', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
