# Generated by Django 4.2 on 2025-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0002_consignments_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='number')),
                ('digit', models.IntegerField(db_column='digit')),
            ],
            options={
                'db_table': 'modules',
                'managed': False,
            },
        ),
    ]
