# Generated by Django 4.2 on 2025-04-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0004_colors_production_codes_alter_consignments_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'model_colors',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
