# Generated by Django 4.2 on 2025-07-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0005_modelcolors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_column='work_date')),
            ],
            options={
                'db_table': 'protocols',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypesOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('order', models.SmallIntegerField(db_column='order')),
            ],
            options={
                'db_table': 'types_of_work',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing', models.CharField(db_column='housing', max_length=3)),
                ('computer_number', models.CharField(db_column='computer_number', max_length=2)),
                ('create_at', models.DateTimeField(db_column='create_at')),
                ('version', models.CharField(db_column='version', max_length=10)),
            ],
            options={
                'db_table': 'workplaces',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
