# Generated by Django 4.2.23 on 2026-10-09 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoffline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineuserroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userroles_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
