# Generated by Django 4.2.23 on 2025-09-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoffline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='update_at',
            field=models.DateTimeField(),
        ),
    ]
